const Array = [
  {
    title: "Model Y",
    subt1: "Model Y Long Range Dual",
    subt2: "Motor All-Wheel Drive",
    subt3: "1,126 mile odometer",
    price: "$49,290",
    prevprice: "$57,990",
    priceMo: "$780 ",
    imgUrl1: "ModelY-1.png",
    imgUrl2: "ModelY-2.png",
    imgUrl3: "ModelY-3.png",
    rangeEst: "318",
    topSpeed: "135",
    testSpeed: "4.8",
    paint: "Red Multi-Coat Paint",
    autopilot: "Autopilot",
    wheels: "20’’ Induction Wheels",
    trial: "30-Day Premium Connectivity Trial",
    interior: "Black and White Premium Interior",
    seat: "Seven Seat Interior",
    tow: "Tow Hitch",
  },

  {
    title: "Model Y",
    subt1: "Model Y Long Range Dual",
    subt2: "Motor All-Wheel Drive",
    subt3: "1,088 mile odometer",
    price: "$47,590",
    prevprice: "$55,990",
    priceMo: "$752 ",
    imgUrl1: "ModelY-1.png",
    imgUrl2: "ModelY-2.png",
    imgUrl3: "ModelY-3.png",
    rangeEst: "318",
    topSpeed: "135",
    testSpeed: "4.8",
    paint: "Red Multi-Coat Paint",
    autopilot: "Autopilot",
    wheels: "20’’ Induction Wheels",
    trial: "30-Day Premium  Connectivity Trial",
    interior: "All Black Premium Interior",
    seat: "Seven Seat Interior",
    tow: false,
  },

  {
    title: "Model Y",
    subt1: "Model Y Rear-Wheel Drive",
    subt2: false,
    subt3: "1,643 mile odometer",
    price: "$40,860",
    prevprice: "$47,990",
    priceMo: "$638 ",
    imgUrl1: "ModelY-1.png",
    imgUrl2: "ModelY-2.png",
    imgUrl3: "ModelY-3.png",
    rangeEst: "242",
    topSpeed: "135",
    testSpeed: "6.6",
    paint: "Red Multi-Coat Paint",
    autopilot: "Autopilot",
    wheels: "20’’ Induction Wheels",
    trial: "30-Day Premium  Connectivity Trial",
    interior: "All Black Premium Interior",
    seat: "Five Seat Interior",
    tow: false,
  },

  {
    title: "Model Y",
    subt1: "Model Y Long Range Dual Motor All-Wheel",
    subt2: "Drive",
    subt3: "3,944 mile odometer",
    price: "$46,860",
    prevprice: "$53,990",
    priceMo: "$739",
    imgUrl1: "ModelY-1.png",
    imgUrl2: "ModelY-2.png",
    imgUrl3: "ModelY-3.png",
    rangeEst: "318",
    topSpeed: "135",
    testSpeed: "4.8",
    paint: "Red Multi-Coat Paint",
    autopilot: "Autopilot",
    wheels: "20’’ Induction Wheels",
    trial: "30-Day Premium  Connectivity Trial",
    interior: "All Black Premium Interior",
    seat: "Five Seat Interior",
    tow: "Tow Hitch",
  },

  {
    title: "Model Y",
    subt1: "Model Y Rear-Wheel Drive",
    subt2: false,
    subt3: "3,286 mile odometer",
    price: "$39,940",
    prevprice: "$46,990",
    priceMo: "$622",
    imgUrl1: "ModelY-black-1.png",
    imgUrl2: "ModelY-black-2.png",
    imgUrl3: "ModelY-black-3.png",
    rangeEst: "260",
    topSpeed: "135",
    testSpeed: "6.6",
    paint: "Solid Black Paint",
    autopilot: "Autopilot",
    wheels: "19’’ Gemini Wheels",
    trial: "30-Day Premium  Connectivity Trial",
    interior: "Black and White Premium Interior",
    seat: "Five Seat Interior",
    tow: false,
  },

  {
    title: "Model Y",
    subt1: "Model Y Long Range Dual Motor All-Wheel Drive",
    subt2: false,
    subt3: "1,083 mile odometer",
    price: "$51,610",
    prevprice: "$57,990",
    priceMo: "820",
    imgUrl1: "ModelY-black-1.png",
    imgUrl2: "ModelY-black-2.png",
    imgUrl3: "ModelY-black-3.png",
    rangeEst: "318",
    topSpeed: "135",
    testSpeed: "4.8",
    paint: "Solid Black Paint",
    autopilot: "Autopilot",
    wheels: "20’’ Induction Wheels",
    trial: "30-Day Premium  Connectivity Trial",
    interior: "Black and White Premium Interior",
    seat: "Seven Seat Interior",
    tow: "Tow Hitch",
  },

  {
    title: "Model Y",
    subt1: "Model Y Rear-Wheel Drive",
    subt2: false,
    subt3: false,
    price: "$42,620",
    prevprice: "$48,990",
    priceMo: "$406",
    imgUrl1: "ModelY-black-1.png",
    imgUrl2: "ModelY-black-2.png",
    imgUrl3: "ModelY-black-3.png",
    rangeEst: "242",
    topSpeed: "135",
    testSpeed: "6.6",
    paint: "Solid Black Paint",
    autopilot: "Autopilot",
    wheels: "20’’ Induction Wheels",
    trial: "30-Day Premium  Connectivity Trial",
    interior: "Black and White Premium Interior",
    seat: "Five Seat Interior",
    tow: false,
  },

  {
    title: "Model S",
    subt1: "Model S Dual Motor All-Wheel Drive",
    subt2: false,
    subt3: "10,480 mile odometer",
    price: "$74,160",
    prevprice: "$81,990",
    priceMo: "$1,201",
    imgUrl1: "ModelS-blue-1.png",
    imgUrl2: "ModelS-blue-2.png",
    imgUrl3: "ModelS-blue-3.png",
    rangeEst: "375",
    topSpeed: "149",
    testSpeed: "3.1",
    paint: "Deep Blue Metallic",
    autopilot: "Autopilot",
    wheels: '21" Arachnid Wheels',
    trial: "1-Year Premium Connectivity Trial",
    interior: "All Black Premium Interior with Ebony Décor",
    seat: "Yoke Steering",
    tow: false,
  },

  {
    title: "Model S",
    subt1: "Model S Plaid",
    subt2: false,
    subt3: "2,104 mile odometer",
    price: "$92,510",
    prevprice: "$97,990",
    priceMo: "$1,511 ",
    imgUrl1: "ModelS-blue-1.png",
    imgUrl2: "ModelS-blue-2.png",
    imgUrl3: "ModelS-blue-3.png",
    rangeEst: "348",
    topSpeed: "200",
    testSpeed: "1.99",
    paint: "Deep Blue Metallic",
    autopilot: "Autopilot",
    wheels: '21" Arachnid Wheels',
    trial: "1-Year Premium Connectivity Trial",
    interior: "Black and White Premium Interior with Carbon Fiber Décor",
    seat: "Steering Wheel",
    tow: false,
  },

  {
    title: "Model S",
    subt1: "Model S Dual Motor All-Wheel Drive",
    subt2: false,
    subt3: "3,618 mile odometer",
    price: "$73,380",
    prevprice: "$78,490",
    priceMo: "$1,187 ",
    imgUrl1: "ModelS-blue-1.png",
    imgUrl2: "ModelS-blue-2.png",
    imgUrl3: "ModelS-blue-3.png",
    rangeEst: "405",
    topSpeed: "149",
    testSpeed: "3.1",
    paint: "Deep Blue Metallic",
    autopilot: "Autopilot",
    wheels: '19" Tempest Wheels',
    trial: "1-Year Premium Connectivity Trial",
    interior: "Cream Premium Interior with Walnut Décor",
    seat: "Steering Wheel",
    tow: false,
  },

  {
    title: "Model S",
    subt1: "Model S Dual Motor All-Wheel Drive",
    subt2: false,
    subt3: "10,089 mile odometer",
    price: "$74,300",
    prevprice: "$81,990",
    priceMo: "$1,203 ",
    imgUrl1: "ModelS-white-1.png",
    imgUrl2: "ModelS-white-2.png",
    imgUrl3: "ModelS-white-3.png",
    rangeEst: "375",
    topSpeed: "149",
    testSpeed: "3.1",
    paint: "Pearl White Multi-Coat Paint",
    autopilot: "Autopilot",
    wheels: '21" Arachnid Wheels',
    trial: "1-Year Premium Connectivity Trial",
    interior: "All Black Premium Interior with Ebony Décor",
    seat: "Yoke Steering",
    tow: false,
  },

  {
    title: "Model S",
    subt1: "Model S Dual Motor All-Wheel Drive",
    subt2: false,
    subt3: "9,389 mile odometer",
    price: "$74,540",
    prevprice: "$81,990",
    priceMo: "$1,207 ",
    imgUrl1: "ModelS-white-1.png",
    imgUrl2: "ModelS-white-2.png",
    imgUrl3: "ModelS-white-3.png",
    rangeEst: "375",
    topSpeed: "149",
    testSpeed: "3.1",
    paint: "Pearl White Multi-Coat Paint",
    autopilot: "Autopilot",
    wheels: '21" Arachnid Wheels',
    trial: "1-Year Premium Connectivity Trial",
    interior: "All Black Premium Interior with Ebony Décor",
    seat: "Yoke Steering",
    tow: false,
  },

  {
    title: "Model S",
    subt1: "Model S Plaid",
    subt2: false,
    subt3: "1,698 mile odometer",
    price: "$93,930",
    prevprice: "$98,990",
    priceMo: "$1,535 ",
    imgUrl1: "ModelS-white-1.png",
    imgUrl2: "ModelS-white-2.png",
    imgUrl3: "ModelS-white-3.png",
    rangeEst: "348",
    topSpeed: "200",
    testSpeed: "1.99",
    paint: "Pearl White Multi-Coat Paint",
    autopilot: "Autopilot",
    wheels: '21" Arachnid Wheels',
    trial: "1-Year Premium Connectivity Trial",
    interior: "Cream Interior with Carbon Fiber Decor",
    seat: "Yoke Steering",
    tow: false,
  },
];

const shuffledArray = Array.sort(() => Math.random() - 0.5);

export default shuffledArray;
